-- =============================================================================
-- V4 — Companies (Phase 2, Super Admin)
--
-- A company IS a company. This migration therefore introduces the tenancy key that
-- every company-owned table in the system already carries: companies.company_id.
--
-- Migration order follows build order: V2 auth, V3 subscription plans, V4 this.
-- Flyway here is forward-only with out-of-order disabled.
--
-- THREE TABLES, TWO KINDS:
--   * companies          PLATFORM-LEVEL. It is the company, so filtering it by
--                        company_id would be circular. No Hibernate filter; access
--                        is restricted to SUPER_ADMIN at the service layer.
--   * company_roles      COMPANY-OWNED. company_id NOT NULL and leading every index.
--   * company_settings   COMPANY-OWNED. Same.
--
-- NOT DONE HERE: the foreign key users.company_id -> companies.company_id. The
-- development database still holds a hand-inserted user row whose company_id
-- matches no company, so adding the constraint would fail the migration on boot.
-- It lands in its own migration once that row is reconciled — tracked in
-- MEMORY/BACKLOG.md. Every other integrity rule below is enforced now.
-- =============================================================================

CREATE TABLE companies (
    id                      BINARY(16)   NOT NULL,

    -- The tenancy key. Generated by the application, never supplied by a caller,
    -- and immutable: every company-owned row in the database points at this value,
    -- so changing it would orphan the company's entire dataset. Deliberately a
    -- different UUID from `id` — a leaked company id is then not a company id.
    company_id               BINARY(16)   NOT NULL,

    -- Stable machine key, uppercased by the application, immutable after creation.
    -- Doubles as the login slug (LoginRequest.companyCode).
    company_code            VARCHAR(50)  NOT NULL,
    company_name            VARCHAR(150) NOT NULL,
    legal_name              VARCHAR(200) NULL,
    display_name            VARCHAR(100) NULL,

    subscription_plan_id    BINARY(16)   NOT NULL,

    -- TRIAL | ACTIVE | INACTIVE | SUSPENDED | EXPIRED. Stored as a string, never an
    -- ordinal, so the enum can be reordered without rewriting rows.
    status                  VARCHAR(20)  NOT NULL,

    trial_start_date        DATE         NULL,
    trial_end_date          DATE         NULL,
    subscription_start_date DATE         NULL,
    subscription_end_date   DATE         NULL,

    email                   VARCHAR(255) NOT NULL,
    mobile                  VARCHAR(20)  NOT NULL,
    alternate_mobile        VARCHAR(20)  NULL,
    website                 VARCHAR(255) NULL,

    -- Tax identifiers. NULL rather than '' when absent, so the unique keys ignore
    -- companies that have not supplied them — MySQL allows repeated NULLs in a
    -- unique index but not repeated empty strings.
    gst_number              VARCHAR(15)  NULL,
    pan_number              VARCHAR(10)  NULL,
    cin_number              VARCHAR(21)  NULL,

    -- URLs. Binary assets belong in object storage, not in InnoDB pages.
    logo                    VARCHAR(500) NULL,
    favicon                 VARCHAR(500) NULL,

    address_line1           VARCHAR(255) NULL,
    address_line2           VARCHAR(255) NULL,
    country                 VARCHAR(100) NULL,
    state                   VARCHAR(100) NULL,
    city                    VARCHAR(100) NULL,
    postal_code             VARCHAR(20)  NULL,

    timezone                VARCHAR(64)  NOT NULL DEFAULT 'Asia/Kolkata',
    currency                VARCHAR(3)   NOT NULL DEFAULT 'INR',
    language                VARCHAR(10)  NOT NULL DEFAULT 'en',
    date_format             VARCHAR(20)  NOT NULL DEFAULT 'dd-MM-yyyy',
    time_format             VARCHAR(20)  NOT NULL DEFAULT 'HH:mm',

    -- Denormalised from status: true while the company may operate. Always derived
    -- by the application, never set independently, or the two disagree.
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    remarks                 VARCHAR(500) NULL,

    created_at TIMESTAMP(6) NOT NULL, created_by BINARY(16) NULL,
    updated_at TIMESTAMP(6) NOT NULL, updated_by BINARY(16) NULL,
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) NULL, deleted_by BINARY(16) NULL,
    version    BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (id),

    -- Global and deliberately NOT scoped by `deleted`: a soft-deleted company keeps
    -- its code, email and tax numbers reserved. Reusing them would let a new company
    -- inherit the identity of a closed one.
    UNIQUE KEY uk_companies_company_id (company_id),
    UNIQUE KEY uk_companies_code (company_code),
    UNIQUE KEY uk_companies_email (email),
    UNIQUE KEY uk_companies_gst (gst_number),
    UNIQUE KEY uk_companies_pan (pan_number),

    KEY idx_companies_status (status, is_active),
    KEY idx_companies_plan (subscription_plan_id),
    KEY idx_companies_name (company_name),
    -- Serves the renewals worklist: WHERE trial_end_date <= ? OR subscription_end_date <= ?
    KEY idx_companies_expiry (subscription_end_date, trial_end_date),

    -- RESTRICT, not CASCADE: plans are soft-deleted, so the row persists, and a plan
    -- must never be removable while companies are billed against it.
    CONSTRAINT fk_companies_subscription_plan
        FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plans (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci
  COMMENT = 'Companies — the company roots of the platform';


-- -----------------------------------------------------------------------------
-- Roles within a company. Seeded with five system roles at creation; a company may
-- re-permission them later, which is exactly why this is a table and not an enum.
-- -----------------------------------------------------------------------------
CREATE TABLE company_roles (
    id          BINARY(16)   NOT NULL,
    company_id   BINARY(16)   NOT NULL,

    role_code   VARCHAR(50)  NOT NULL,
    role_name   VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,

    -- Seeded by the platform: editable, never deletable. A company with no
    -- COMPANY_ADMIN role has nobody who can administer it.
    system_role BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP(6) NOT NULL, created_by BINARY(16) NULL,
    updated_at TIMESTAMP(6) NOT NULL, updated_by BINARY(16) NULL,
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) NULL, deleted_by BINARY(16) NULL,
    version    BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
    -- Per company, never global: two companies may both have a role called SUPERVISOR.
    UNIQUE KEY uk_company_roles_company_code (company_id, role_code),
    KEY idx_company_roles_company (company_id, is_active),

    CONSTRAINT fk_company_roles_company
        FOREIGN KEY (company_id) REFERENCES companies (company_id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci
  COMMENT = 'Per-company roles';


-- Permissions of a role, as an element collection. No company_id of its own:
-- isolation comes from the owning role row, which is company-filtered, and the FK
-- cascades so a deleted role cannot leave orphaned grants.
CREATE TABLE company_role_permissions (
    role_id    BINARY(16)  NOT NULL,
    permission VARCHAR(50) NOT NULL,

    PRIMARY KEY (role_id, permission),
    CONSTRAINT fk_company_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES company_roles (id)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci
  COMMENT = 'Permissions granted by each company role';


-- -----------------------------------------------------------------------------
-- Company configuration. Key/value rather than a column per setting: settings are
-- added constantly and by different modules, and a column each means a migration
-- each time.
-- -----------------------------------------------------------------------------
CREATE TABLE company_settings (
    id            BINARY(16)   NOT NULL,
    company_id     BINARY(16)   NOT NULL,

    setting_key   VARCHAR(100) NOT NULL,
    setting_value VARCHAR(500) NULL,
    category      VARCHAR(50)  NOT NULL,

    -- Copied from the subscription plan rather than chosen by the company: quotas
    -- are the obvious case, since a company must not raise its own user limit.
    -- An empty value on a limit.* key means UNLIMITED, matching the plan's
    -- null-means-unlimited convention.
    plan_derived  BOOLEAN      NOT NULL DEFAULT FALSE,
    description   VARCHAR(255) NULL,

    created_at TIMESTAMP(6) NOT NULL, created_by BINARY(16) NULL,
    updated_at TIMESTAMP(6) NOT NULL, updated_by BINARY(16) NULL,
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) NULL, deleted_by BINARY(16) NULL,
    version    BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
    UNIQUE KEY uk_company_settings_company_key (company_id, setting_key),
    KEY idx_company_settings_company_category (company_id, category),

    CONSTRAINT fk_company_settings_company
        FOREIGN KEY (company_id) REFERENCES companies (company_id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci
  COMMENT = 'Per-company configuration';
